<?
$aMenuLinks = array(
    array(
        "О Квартале",
        "/quarter.php",
        array(),
        array(),
        ""
    ),
    array(
        "О застройщике",
        "/developer.php",
        array(),
        array(),
        ""
    ),
    array(
        "Документация",
        "/documents.php",
        array(),
        array(),
        ""
    ),
    array(
        "Квартиры",
        "/apartments.php",
        array(),
        array(),
        ""
    ),
    array(
        "Галерея",
        "/",
        array(),
        array(),
        ""
    ),
    array(
        "Новости",
        "news",
        array(),
        array(),
        ""
    ),
    array(
        "Ритейл",
        "/retail.php",
        array(),
        array(),
        ""
    ),
    array(
        "Экскурсии",
        "/tour.php",
        array(),
        array(),
        ""
    ),
    array(
        "Риелторам",
        "/realtors.phpp",
        array(),
        array(),
        ""
    ),
    array(
        "Как купить",
        "/how-buy.php",
        array(),
        array(),
        ""
    ),
    array(
        "Ремонт",
        "/repairs.php",
        array(),
        array(),
        ""
    ),
    array(
        "Контакты",
        "/documents.php",
        array(),
        array(),
        ""
    ),
    array(
        "",
        "",
        array(),
        array(),
        ""
    ),
    array(
        "Ход строительства",
        "/building.php",
        array(),
        array(),
        ""
    )
);
?>